server:
  port: 8084
spring:
  application:
    name: transaction-service

  datasource:
    url: jdbc:postgresql://localhost:5432/transaction_service
    username: Tienld
    password: 123456
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update   # validate | update | create | create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

service:
  wallet-service:
    url: "http://localhost:8082"
user-service:
  url: "http://localhost:8081"
internal:
  secret: "${INTERNAL_SECRET:internal-secret}"
